# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commitHistory = QtWidgets.QListView(self.centralwidget)
        self.commitHistory.setGeometry(QtCore.QRect(490, 10, 401, 541))
        self.commitHistory.setObjectName("commitHistory")
        self.branchBox = QtWidgets.QComboBox(self.centralwidget)
        self.branchBox.setGeometry(QtCore.QRect(320, 50, 161, 31))
        self.branchBox.setObjectName("branchBox")
        self.branchLabel = QtWidgets.QLabel(self.centralwidget)
        self.branchLabel.setGeometry(QtCore.QRect(320, 10, 101, 41))
        self.branchLabel.setAcceptDrops(False)
        self.branchLabel.setScaledContents(False)
        self.branchLabel.setObjectName("branchLabel")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(320, 90, 161, 461))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(100, 10, 81, 41))
        self.titleLabel.setObjectName("titleLabel")
        self.commitButton = QtWidgets.QPushButton(self.centralwidget)
        self.commitButton.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.commitButton.setObjectName("commitButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pullButton = QtWidgets.QPushButton(self.centralwidget)
        self.pullButton.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.pullButton.setObjectName("pullButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.branchLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Branch:</span></p></body></html>"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">GitBit</span></p></body></html>"))
        self.commitButton.setText(_translate("MainWindow", "Commit"))
        self.pushButton.setText(_translate("MainWindow", "Push"))
        self.pullButton.setText(_translate("MainWindow", "Pull"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
